spring:
  application:
    name: delivery

  datasource:
    username: myuser
    password: 12345
    url: jdbc:postgresql://localhost:5433/mydb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  grpc:
    geo-service:
      host: ${DISCOUNT_SERVICE_GRPC_HOST:0.0.0.0}
      port: ${DISCOUNT_SERVICE_GRPC_PORT:5004}
