spring:
  application:
    name: delivery

  datasource:
    username: myuser
    password: 12345
    url: jdbc:postgresql://localhost:5433/mydb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect